services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-CU28-ubuntu-20.04"
    entrypoint: /mssql/entrypoint.sh
    command: /opt/mssql/bin/sqlservr
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ../mssql:/mssql
    ports:
      - "15785:1433"
    healthcheck:
        # The OPENCoronaTempTables database is initialised last, so check that
        # we can connect to that db specifically
        test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "Your_password123!" -d "OPENCoronaTempTables" -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s

  base:
    build:
      context: ..
      # path relative to context
      dockerfile: docker/Dockerfile
      # the production stage in the Dockerfile
      target: tpp-database-utils-prod # CHANGE ME!
      args:
        # this makes the image work for later cache_from: usage
        - BUILDKIT_INLINE_CACHE=1
        # dynamic env vars supplied by just
        - BUILD_DATE
        - GITREF
        # env vars from .env
        - UBUNTU_VERSION
        - UV_VERSION
    # use dockers builitin PID daemon
    init: true


  # prod service. Used to build prod image and run/test it locally
  prod:
    # image name, both locally and public
    image: tpp-database-utils
    extends:
      service: base
    # this compose file is only used for production-like testing - so we
    # don't worry about potentially leaking dummy env vars into actual prod
    env_file: .env

  # base development service
  # broken out so we can have a common base for dev and test since depends_on
  # can't be used in the target of an extends
  dev-base:
    extends:
      service: base
    image: tpp-database-utils-dev
    build:
      # the dev stage in the Dockerfile
      target: tpp-database-utils-dev
      args:
        # user developer uid:gid in dev
        - USERID=${DEV_USERID:-1000}
        - GROUPID=${DEV_GROUPID:-1000}
    # paths relative to docker-compose.yaml file
    env_file: .env
    volumes:
      # Note: paths are relative to the *docker-compose* file
      - ..:/app

  dev:
    extends:
      service: dev-base

  # test runner service - uses dev-image with a different commnd
  test:
    extends:
      service: dev-base
    command: /app/scripts/run-tests.sh
    depends_on:
      mssql:
        condition: service_healthy
